/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UseCasesRouteImport } from './routes/use-cases'
import { Route as StorageRouteImport } from './routes/storage'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as MaintRouteImport } from './routes/maint'
import { Route as LatencyRouteImport } from './routes/latency'
import { Route as IntegrationsRouteImport } from './routes/integrations'
import { Route as EngineRouteImport } from './routes/engine'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as CostRouteImport } from './routes/cost'
import { Route as ConfigRouteImport } from './routes/config'
import { Route as ChangelogRouteImport } from './routes/changelog'
import { Route as ArchitectureRouteImport } from './routes/architecture'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as AboutIndexRouteImport } from './routes/about/index'
import { Route as SolutionsLocalRagRouteImport } from './routes/solutions/local-rag'
import { Route as SolutionsAiIdeToolingRouteImport } from './routes/solutions/ai-ide-tooling'
import { Route as SolutionsAiAgentsRouteImport } from './routes/solutions/ai-agents'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'
import { Route as AboutContactRouteImport } from './routes/about/contact'
import { Route as AboutCompanyRouteImport } from './routes/about/company'
import { Route as AboutCommunityRouteImport } from './routes/about/community'

const UseCasesRoute = UseCasesRouteImport.update({
  id: '/use-cases',
  path: '/use-cases',
  getParentRoute: () => rootRouteImport,
} as any)
const StorageRoute = StorageRouteImport.update({
  id: '/storage',
  path: '/storage',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const MaintRoute = MaintRouteImport.update({
  id: '/maint',
  path: '/maint',
  getParentRoute: () => rootRouteImport,
} as any)
const LatencyRoute = LatencyRouteImport.update({
  id: '/latency',
  path: '/latency',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsRoute = IntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => rootRouteImport,
} as any)
const EngineRoute = EngineRouteImport.update({
  id: '/engine',
  path: '/engine',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const CostRoute = CostRouteImport.update({
  id: '/cost',
  path: '/cost',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigRoute = ConfigRouteImport.update({
  id: '/config',
  path: '/config',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangelogRoute = ChangelogRouteImport.update({
  id: '/changelog',
  path: '/changelog',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchitectureRoute = ArchitectureRouteImport.update({
  id: '/architecture',
  path: '/architecture',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutIndexRoute = AboutIndexRouteImport.update({
  id: '/about/',
  path: '/about/',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsLocalRagRoute = SolutionsLocalRagRouteImport.update({
  id: '/solutions/local-rag',
  path: '/solutions/local-rag',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsAiIdeToolingRoute = SolutionsAiIdeToolingRouteImport.update({
  id: '/solutions/ai-ide-tooling',
  path: '/solutions/ai-ide-tooling',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsAiAgentsRoute = SolutionsAiAgentsRouteImport.update({
  id: '/solutions/ai-agents',
  path: '/solutions/ai-agents',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutContactRoute = AboutContactRouteImport.update({
  id: '/about/contact',
  path: '/about/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutCompanyRoute = AboutCompanyRouteImport.update({
  id: '/about/company',
  path: '/about/company',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutCommunityRoute = AboutCommunityRouteImport.update({
  id: '/about/community',
  path: '/about/community',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/architecture': typeof ArchitectureRoute
  '/changelog': typeof ChangelogRoute
  '/config': typeof ConfigRoute
  '/cost': typeof CostRoute
  '/docs': typeof DocsRoute
  '/engine': typeof EngineRoute
  '/integrations': typeof IntegrationsRoute
  '/latency': typeof LatencyRoute
  '/maint': typeof MaintRoute
  '/pricing': typeof PricingRoute
  '/storage': typeof StorageRoute
  '/use-cases': typeof UseCasesRoute
  '/about/community': typeof AboutCommunityRoute
  '/about/company': typeof AboutCompanyRoute
  '/about/contact': typeof AboutContactRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/solutions/ai-agents': typeof SolutionsAiAgentsRoute
  '/solutions/ai-ide-tooling': typeof SolutionsAiIdeToolingRoute
  '/solutions/local-rag': typeof SolutionsLocalRagRoute
  '/about/': typeof AboutIndexRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/architecture': typeof ArchitectureRoute
  '/changelog': typeof ChangelogRoute
  '/config': typeof ConfigRoute
  '/cost': typeof CostRoute
  '/docs': typeof DocsRoute
  '/engine': typeof EngineRoute
  '/integrations': typeof IntegrationsRoute
  '/latency': typeof LatencyRoute
  '/maint': typeof MaintRoute
  '/pricing': typeof PricingRoute
  '/storage': typeof StorageRoute
  '/use-cases': typeof UseCasesRoute
  '/about/community': typeof AboutCommunityRoute
  '/about/company': typeof AboutCompanyRoute
  '/about/contact': typeof AboutContactRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/solutions/ai-agents': typeof SolutionsAiAgentsRoute
  '/solutions/ai-ide-tooling': typeof SolutionsAiIdeToolingRoute
  '/solutions/local-rag': typeof SolutionsLocalRagRoute
  '/about': typeof AboutIndexRoute
  '/blog': typeof BlogIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/architecture': typeof ArchitectureRoute
  '/changelog': typeof ChangelogRoute
  '/config': typeof ConfigRoute
  '/cost': typeof CostRoute
  '/docs': typeof DocsRoute
  '/engine': typeof EngineRoute
  '/integrations': typeof IntegrationsRoute
  '/latency': typeof LatencyRoute
  '/maint': typeof MaintRoute
  '/pricing': typeof PricingRoute
  '/storage': typeof StorageRoute
  '/use-cases': typeof UseCasesRoute
  '/about/community': typeof AboutCommunityRoute
  '/about/company': typeof AboutCompanyRoute
  '/about/contact': typeof AboutContactRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/solutions/ai-agents': typeof SolutionsAiAgentsRoute
  '/solutions/ai-ide-tooling': typeof SolutionsAiIdeToolingRoute
  '/solutions/local-rag': typeof SolutionsLocalRagRoute
  '/about/': typeof AboutIndexRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/architecture'
    | '/changelog'
    | '/config'
    | '/cost'
    | '/docs'
    | '/engine'
    | '/integrations'
    | '/latency'
    | '/maint'
    | '/pricing'
    | '/storage'
    | '/use-cases'
    | '/about/community'
    | '/about/company'
    | '/about/contact'
    | '/blog/$slug'
    | '/solutions/ai-agents'
    | '/solutions/ai-ide-tooling'
    | '/solutions/local-rag'
    | '/about/'
    | '/blog/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/architecture'
    | '/changelog'
    | '/config'
    | '/cost'
    | '/docs'
    | '/engine'
    | '/integrations'
    | '/latency'
    | '/maint'
    | '/pricing'
    | '/storage'
    | '/use-cases'
    | '/about/community'
    | '/about/company'
    | '/about/contact'
    | '/blog/$slug'
    | '/solutions/ai-agents'
    | '/solutions/ai-ide-tooling'
    | '/solutions/local-rag'
    | '/about'
    | '/blog'
  id:
    | '__root__'
    | '/'
    | '/architecture'
    | '/changelog'
    | '/config'
    | '/cost'
    | '/docs'
    | '/engine'
    | '/integrations'
    | '/latency'
    | '/maint'
    | '/pricing'
    | '/storage'
    | '/use-cases'
    | '/about/community'
    | '/about/company'
    | '/about/contact'
    | '/blog/$slug'
    | '/solutions/ai-agents'
    | '/solutions/ai-ide-tooling'
    | '/solutions/local-rag'
    | '/about/'
    | '/blog/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArchitectureRoute: typeof ArchitectureRoute
  ChangelogRoute: typeof ChangelogRoute
  ConfigRoute: typeof ConfigRoute
  CostRoute: typeof CostRoute
  DocsRoute: typeof DocsRoute
  EngineRoute: typeof EngineRoute
  IntegrationsRoute: typeof IntegrationsRoute
  LatencyRoute: typeof LatencyRoute
  MaintRoute: typeof MaintRoute
  PricingRoute: typeof PricingRoute
  StorageRoute: typeof StorageRoute
  UseCasesRoute: typeof UseCasesRoute
  AboutCommunityRoute: typeof AboutCommunityRoute
  AboutCompanyRoute: typeof AboutCompanyRoute
  AboutContactRoute: typeof AboutContactRoute
  BlogSlugRoute: typeof BlogSlugRoute
  SolutionsAiAgentsRoute: typeof SolutionsAiAgentsRoute
  SolutionsAiIdeToolingRoute: typeof SolutionsAiIdeToolingRoute
  SolutionsLocalRagRoute: typeof SolutionsLocalRagRoute
  AboutIndexRoute: typeof AboutIndexRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/use-cases': {
      id: '/use-cases'
      path: '/use-cases'
      fullPath: '/use-cases'
      preLoaderRoute: typeof UseCasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/storage': {
      id: '/storage'
      path: '/storage'
      fullPath: '/storage'
      preLoaderRoute: typeof StorageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maint': {
      id: '/maint'
      path: '/maint'
      fullPath: '/maint'
      preLoaderRoute: typeof MaintRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/latency': {
      id: '/latency'
      path: '/latency'
      fullPath: '/latency'
      preLoaderRoute: typeof LatencyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations': {
      id: '/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof IntegrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/engine': {
      id: '/engine'
      path: '/engine'
      fullPath: '/engine'
      preLoaderRoute: typeof EngineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cost': {
      id: '/cost'
      path: '/cost'
      fullPath: '/cost'
      preLoaderRoute: typeof CostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/config': {
      id: '/config'
      path: '/config'
      fullPath: '/config'
      preLoaderRoute: typeof ConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/changelog': {
      id: '/changelog'
      path: '/changelog'
      fullPath: '/changelog'
      preLoaderRoute: typeof ChangelogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/architecture': {
      id: '/architecture'
      path: '/architecture'
      fullPath: '/architecture'
      preLoaderRoute: typeof ArchitectureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/': {
      id: '/about/'
      path: '/about'
      fullPath: '/about/'
      preLoaderRoute: typeof AboutIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/local-rag': {
      id: '/solutions/local-rag'
      path: '/solutions/local-rag'
      fullPath: '/solutions/local-rag'
      preLoaderRoute: typeof SolutionsLocalRagRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/ai-ide-tooling': {
      id: '/solutions/ai-ide-tooling'
      path: '/solutions/ai-ide-tooling'
      fullPath: '/solutions/ai-ide-tooling'
      preLoaderRoute: typeof SolutionsAiIdeToolingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/ai-agents': {
      id: '/solutions/ai-agents'
      path: '/solutions/ai-agents'
      fullPath: '/solutions/ai-agents'
      preLoaderRoute: typeof SolutionsAiAgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/contact': {
      id: '/about/contact'
      path: '/about/contact'
      fullPath: '/about/contact'
      preLoaderRoute: typeof AboutContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/company': {
      id: '/about/company'
      path: '/about/company'
      fullPath: '/about/company'
      preLoaderRoute: typeof AboutCompanyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/community': {
      id: '/about/community'
      path: '/about/community'
      fullPath: '/about/community'
      preLoaderRoute: typeof AboutCommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArchitectureRoute: ArchitectureRoute,
  ChangelogRoute: ChangelogRoute,
  ConfigRoute: ConfigRoute,
  CostRoute: CostRoute,
  DocsRoute: DocsRoute,
  EngineRoute: EngineRoute,
  IntegrationsRoute: IntegrationsRoute,
  LatencyRoute: LatencyRoute,
  MaintRoute: MaintRoute,
  PricingRoute: PricingRoute,
  StorageRoute: StorageRoute,
  UseCasesRoute: UseCasesRoute,
  AboutCommunityRoute: AboutCommunityRoute,
  AboutCompanyRoute: AboutCompanyRoute,
  AboutContactRoute: AboutContactRoute,
  BlogSlugRoute: BlogSlugRoute,
  SolutionsAiAgentsRoute: SolutionsAiAgentsRoute,
  SolutionsAiIdeToolingRoute: SolutionsAiIdeToolingRoute,
  SolutionsLocalRagRoute: SolutionsLocalRagRoute,
  AboutIndexRoute: AboutIndexRoute,
  BlogIndexRoute: BlogIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
